library(ggplot2)
library(lubridate)
library(reshape2)
library(scales)
library(DirichletReg)
require(mgcv)
require(nlme)
library(splines)
library(MASS)
library(forecast)
library(stringr)
library(doMC)
library(digest)
library(XML)
library(directlabels)
library(testthat)
library(plyr)
library(coefplot)
library(mnormt)
library(plyr)
library(stringr)
library(scales)
library(coda)
library(directlabels)
library(RJSONIO)
registerDoMC(4)
getDoParWorkers()
theme_set(theme_bw())
options(stringAsFactors = FALSE)


